name: dev branch auto ci process script

on: # 아래 job을 실행시킬 상황
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: Ubuntu 22.04.4 LTS # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.SERVER_IP }} # 인스턴스 IP
          username: ${{ secrets.SERVER_USER }} # 우분투 아이디
          key: ${{ secrets.SERVER_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.SERVER_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/TripWeb_project
            git pull origin main
            pm2 kill
            cd trip_web_front
            npm i --force
            npm run build
            pm2 serve build 3000 --name trip-web_front
            cd ../trip-web_backend/
            npm i --force
            nest build
            pm2 start dist/main.js